// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Post struct {
	ID              uuid.UUID
	Title           string
	Slug            string
	MarkdownContent string
	MetaDescription sql.NullString
	CoverImageUrl   sql.NullString
	YoutubeLinks    pqtype.NullRawMessage
	PublishedAt     sql.NullTime
	UserID          uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
	Revoked   bool
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
