// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
  title,
  slug,
  markdown_content,
  meta_description,
  cover_image_url,
  youtube_links,
  published_at,
  user_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, title, slug, markdown_content, meta_description, cover_image_url, youtube_links, published_at, user_id, created_at, updated_at
`

type CreatePostParams struct {
	Title           string
	Slug            string
	MarkdownContent string
	MetaDescription sql.NullString
	CoverImageUrl   sql.NullString
	YoutubeLinks    pqtype.NullRawMessage
	PublishedAt     sql.NullTime
	UserID          uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Title,
		arg.Slug,
		arg.MarkdownContent,
		arg.MetaDescription,
		arg.CoverImageUrl,
		arg.YoutubeLinks,
		arg.PublishedAt,
		arg.UserID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.MarkdownContent,
		&i.MetaDescription,
		&i.CoverImageUrl,
		&i.YoutubeLinks,
		&i.PublishedAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
